vector1 <- c()
vector2 <- c(1, 1, 1, 1, 1)
vector3 <- c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
vector4 <- c(1, 5, 10, 20, 30, 50)
vector5 <- c(10, 50, 100, 200, 300, 500)
vector6 <- c(1000)
vector7 <- c(0, 1, 2, 3, 4, 5)
vector8 <- c(0, 0, 0, 0, 0)
vector9 <- c(-1, 10, 20, 30, 50)
vector10<- c(-10, -10, -10, -10, -10)


gini(vector1, corr = TRUE)
DescTools::Gini(vector1)
gini(vector2, corr = TRUE)
DescTools::Gini(vector2)
gini(vector3, corr = TRUE)
DescTools::Gini(vector3)
gini(vector4, corr = TRUE)
DescTools::Gini(vector4)
gini(vector5, corr = TRUE)
DescTools::Gini(vector5)
gini(vector6, corr = TRUE)
DescTools::Gini(vector6)
gini(vector7, corr = TRUE)
DescTools::Gini(vector7)
gini(vector8, corr = TRUE)
DescTools::Gini(vector8)
gini(vector9, corr = TRUE)
DescTools::Gini(vector9)
gini(vector10, corr = TRUE)
DescTools::Gini(vector10)


hoover(vector1)
REAT::hoover(vector1)
hoover(vector2)
REAT::hoover(vector2)
hoover(vector3)
REAT::hoover(vector3)
hoover(vector4)
REAT::hoover(vector4)
hoover(vector5)
REAT::hoover(vector5)
hoover(vector6)
REAT::hoover(vector6)
hoover(vector7)
REAT::hoover(vector7)
hoover(vector8)
REAT::hoover(vector8)
hoover(vector9)
REAT::hoover(vector9)
hoover(vector10)
REAT::hoover(vector10)

rosenbluth(vector1)
DescTools::Rosenbluth(vector1)
rosenbluth(vector2)
DescTools::Rosenbluth(vector2)
rosenbluth(vector3)
DescTools::Rosenbluth(vector3)
rosenbluth(vector4)
DescTools::Rosenbluth(vector4)
rosenbluth(vector5)
DescTools::Rosenbluth(vector5)
rosenbluth(vector6)
DescTools::Rosenbluth(vector6)
rosenbluth(vector7)
DescTools::Rosenbluth(vector7)
rosenbluth(vector8)
DescTools::Rosenbluth(vector8)
rosenbluth(vector9)
DescTools::Rosenbluth(vector9)
rosenbluth(vector10)
DescTools::Rosenbluth(vector10)

hhi(vector1)
DescTools::Herfindahl(vector1)
hhi(vector2)
DescTools::Herfindahl(vector2)
hhi(vector3)
DescTools::Herfindahl(vector3)
hhi(vector4)
DescTools::Herfindahl(vector4)
hhi(vector5)
DescTools::Herfindahl(vector5)
hhi(vector6)
DescTools::Herfindahl(vector6)
hhi(vector7)
DescTools::Herfindahl(vector7)
hhi(vector8)
DescTools::Herfindahl(vector8)
hhi(vector9)
DescTools::Herfindahl(vector9)
hih(vector10)
DescTools::Herfindahl(vector10)

DescTools::Entropy(vector1, base = 2)
shannon(vector1)
DescTools::Entropy(vector2, base = 2)
shannon(vector2)
DescTools::Entropy(vector3, base = 2)
shannon(vector3)
DescTools::Entropy(vector4, base = 2)
shannon(vector4)
DescTools::Entropy(vector5, base = 2)
shannon(vector5)
DescTools::Entropy(vector6, base = 2)
shannon(vector6)
DescTools::Entropy(vector7, base = 2)
shannon(vector7)
DescTools::Entropy(vector8, base = 2)
shannon(vector8)
DescTools::Entropy(vector9, base = 2)
shannon(vector9)
DescTools::Entropy(vector10, base = 2)
shannon(vector10)

myatkinson(vector1, epsilon=1)
DescTools::Atkinson(vector1, parameter=1)
myatkinson(vector2, epsilon=1)
DescTools::Atkinson(vector2, parameter=1)
myatkinson(vector3, epsilon=1)
DescTools::Atkinson(vector3, parameter=1)
myatkinson(vector4, epsilon=1)
DescTools::Atkinson(vector4, parameter=1)
myatkinson(vector5, epsilon=1)
DescTools::Atkinson(vector5, parameter=1)
myatkinson(vector6, epsilon=1)
DescTools::Atkinson(vector6, parameter=1)
myatkinson(vector7, epsilon=1)
DescTools::Atkinson(vector7, parameter=1)
myatkinson(vector8, epsilon=1)
DescTools::Atkinson(vector8, parameter=1)
myatkinson(vector9, epsilon=1)
DescTools::Atkinson(vector9, parameter=1)
myatkinson(vector10, epsilon=1)
DescTools::Atkinson(vector10, parameter=1)

myatkinson(vector1, epsilon=0.5)
DescTools::Atkinson(vector1, parameter=0.5)
myatkinson(vector2, epsilon=0.5)
DescTools::Atkinson(vector2, parameter=0.5)
myatkinson(vector3, epsilon=0.5)
DescTools::Atkinson(vector3, parameter=0.5)
myatkinson(vector4, epsilon=0.5)
DescTools::Atkinson(vector4, parameter=0.5)
myatkinson(vector5, epsilon=0.5)
DescTools::Atkinson(vector5, parameter=0.5)
myatkinson(vector6, epsilon=0.5)
DescTools::Atkinson(vector6, parameter=0.5)
myatkinson(vector7, epsilon=0.5)
DescTools::Atkinson(vector7, parameter=0.5)
myatkinson(vector8, epsilon=0.5)
DescTools::Atkinson(vector8, parameter=0.5)
myatkinson(vector9, epsilon=0.5)
DescTools::Atkinson(vector9, parameter=0.5)
myatkinson(vector10, epsilon=0.5)
DescTools::Atkinson(vector10, parameter=0.5)

myatkinson(vector1, epsilon=2)
DescTools::Atkinson(vector1, parameter=2)
myatkinson(vector2, epsilon=2)
DescTools::Atkinson(vector2, parameter=2)
myatkinson(vector3, epsilon=2)
DescTools::Atkinson(vector3, parameter=2)
myatkinson(vector4, epsilon=2)
DescTools::Atkinson(vector4, parameter=2)
myatkinson(vector5, epsilon=2)
DescTools::Atkinson(vector5, parameter=2)
myatkinson(vector6, epsilon=2)
DescTools::Atkinson(vector6, parameter=2)
myatkinson(vector7, epsilon=2)
DescTools::Atkinson(vector7, parameter=2)
myatkinson(vector8, epsilon=2)
DescTools::Atkinson(vector8, parameter=2)
myatkinson(vector9, epsilon=2)
DescTools::Atkinson(vector9, parameter=2)
myatkinson(vector10, epsilon=2)
DescTools::Atkinson(vector10, parameter=2)

gei(vector1, alpha = 1)
IC2::calcGEI(vector1, alpha = 1)
gei(vector2, alpha = 1)
IC2::calcGEI(vector2, alpha = 1)
gei(vector3, alpha = 1)
IC2::calcGEI(vector3, alpha = 1)
gei(vector4, alpha = 1)
IC2::calcGEI(vector4, alpha = 1)
gei(vector5, alpha = 1)
IC2::calcGEI(vector5, alpha = 1)
gei(vector6, alpha = 1)
IC2::calcGEI(vector6, alpha = 1)
gei(vector7, alpha = 1)
IC2::calcGEI(vector7, alpha = 1)
gei(vector8, alpha = 1)
IC2::calcGEI(vector8, alpha = 1)
gei(vector9, alpha = 1)
IC2::calcGEI(vector9, alpha = 1)
gei(vector10, alpha = 1)
IC2::calcGEI(vector10, alpha = 1)

gei(vector1, alpha = 0)
IC2::calcGEI(vector1, alpha = 0)
gei(vector2, alpha = 0)
IC2::calcGEI(vector2, alpha = 0)
gei(vector3, alpha = 0)
IC2::calcGEI(vector3, alpha = 0)
gei(vector4, alpha = 0)
IC2::calcGEI(vector4, alpha = 0)
gei(vector5, alpha = 0)
IC2::calcGEI(vector5, alpha = 0)
gei(vector6, alpha = 0)
IC2::calcGEI(vector6, alpha = 0)
gei(vector7, alpha = 0)
IC2::calcGEI(vector7, alpha = 0)
gei(vector8, alpha = 0)
IC2::calcGEI(vector8, alpha = 0)
gei(vector9, alpha = 0)
IC2::calcGEI(vector9, alpha = 0)
gei(vector10, alpha = 0)
IC2::calcGEI(vector10, alpha = 0)

gei(vector1, alpha = -1)
IC2::calcGEI(vector1, alpha = -1)
gei(vector2, alpha = -1)
IC2::calcGEI(vector2, alpha = -1)
gei(vector3, alpha = -1)
IC2::calcGEI(vector3, alpha = -1)
gei(vector4, alpha = -1)
IC2::calcGEI(vector4, alpha = -1)
gei(vector5, alpha = -1)
IC2::calcGEI(vector5, alpha = -1)
gei(vector6, alpha = -1)
IC2::calcGEI(vector6, alpha = -1)
gei(vector7, alpha = -1)
IC2::calcGEI(vector7, alpha = -1)
gei(vector8, alpha = -1)
IC2::calcGEI(vector8, alpha = -1)
gei(vector9, alpha = -1)
IC2::calcGEI(vector9, alpha = -1)
gei(vector10, alpha = -1)
IC2::calcGEI(vector10, alpha = -1)

gei(vector1, alpha = 0.5)
IC2::calcGEI(vector1, alpha = 0.5)
gei(vector2, alpha = 0.5)
IC2::calcGEI(vector2, alpha = 0.5)
gei(vector3, alpha = 0.5)
IC2::calcGEI(vector3, alpha = 0.5)
gei(vector4, alpha = 0.5)
IC2::calcGEI(vector4, alpha = 0.5)
gei(vector5, alpha = 0.5)
IC2::calcGEI(vector5, alpha = 0.5)
gei(vector6, alpha = 0.5)
IC2::calcGEI(vector6, alpha = 0.5)
gei(vector7, alpha = 0.5)
IC2::calcGEI(vector7, alpha = 0.5)
gei(vector8, alpha = 0.5)
IC2::calcGEI(vector8, alpha = 0.5)
gei(vector9, alpha = 0.5)
IC2::calcGEI(vector9, alpha = 0.5)
gei(vector10, alpha = 0.5)
IC2::calcGEI(vector10, alpha = 0.5)












